from django.urls import path

from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.index, name='index'),
    path('me/', views.UserProfileView.as_view(), name='user'),
    path('me/employment/', views.UserEmploymentOverviewView.as_view(), name='user-employment'),
    path('me/leave_organization/<int:employee>/',
         views.LeaveCorporationView.as_view(), name='user-employee-leave'),
    path('me/discord/', views.discord_connect,
         name='user-discord-connect'),
    path('me/invite/<int:pk>/<str:action>/', views.EmployeeInviteView.as_view(),
         name='user-employee-invite'),
    path('account/', views.AccountListView.as_view(), name='account'),
    path('account/new/', views.account_creation_chooser,
         name='account-create'),
    path('account/new/personal/', views.PersonalAccountCreateView.as_view(),
         name='account-create-personal'),
    path('account/new/corporate/', views.CorporateAccountCreateView.as_view(),
         name='account-create-corporate'),
    path('account/<uuid:pk>/', views.AccountDetailView.as_view(),
         name='account-detail'),
    path('account/<uuid:pk>/edit/', views.AccountUpdateView.as_view(),
         name='account-update'),
    path('account/<uuid:pk>/delete/',
         views.AccountDeleteView.as_view(), name='account-delete'),
    path('transaction/new/', views.TransactionCreateView.as_view(),
         name='account-transaction-create'),
    path('transaction/confirm/', views.TransactionConfirmView.as_view(),
         name='account-transaction-confirm'),
    path('transaction/<uuid:pk>/', views.TransactionDetailView.as_view(),
         name='account-transaction-detail'),
    path('organization/', views.CorporationListView.as_view(),
         name='corporation-list'),
    path('organization/new/', views.CorporationCreateView.as_view(),
         name='corporation-create'),
    path('organization/<str:pk>/', views.CorporationDetailView.as_view(),
         name='corporation-detail'),
    path('organization/<str:pk>/delete/',
         views.CorporationDeleteView.as_view(), name='corporation-delete'),
    path('organization/<str:pk>/edit/',
         views.CorporateUpdateView.as_view(), name='corporation-update'),
    path('organization/<str:pk>/employees/',
         views.ManageEmployeeView.as_view(), name='corporation-employees'),
    path('organization/<str:pk>/employees/fire/<int:employee>/',
         views.FireEmployeeView.as_view(), name='corporation-employees-fire'),
    path('organization/<str:pk>/employees/transfer/<int:employee>/',
         views.TransferOwnershipView.as_view(), name='corporation-employees-transfer-ownership'),
    path('marketplace/', views.MarketplaceView.as_view(), name='marketplace'),
    path('discord/', views.discord_callback, name='user-discord-callback'),
    path('u/<int:discord_id>', views.bot_resubmit_view, name='bot-resubmit')
]
