# Generated by Django 3.1.6 on 2021-03-29 12:56

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CIV', 'Civilization Coin')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='ottoman_threshold_variable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='nation',
            field=models.CharField(choices=[('JP', 'Japan')], default='JP', help_text='Select the nation you operate out of. Different nations may have different laws on things like corporate tax.', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CIV', 'Civilization Coin')], default='XYZ', editable=False, max_length=3),
        ),
    ]
